function txt = gui_txt(parent,position,string,fontsize,tooltip,align,tag)

txt = uicontrol('Parent',parent,'Style','text','Units','pixels',...
          'Position',position,'String',string,'TooltipString',tooltip,...
          'HorizontalAlignment',align,'Fontsize',fontsize,'Tag',tag);