function var = gui_table(parent,position,cNames,cFormat,cWidth,cEditable,rNames,tag,action)
    z = 255;
    var = uitable('Parent',parent,'Units','pixels','Position', position,...
                  'ColumnName', cNames, 'ColumnFormat', cFormat, 'ColumnWidth',cWidth,...
                  'ColumnEditable', cEditable, 'RowName',rNames,'Tag',tag,'RowStriping','on',...
                  'BackgroundColor', [246/z 246/z 246/z; 176/z 221/z 255/z],'CellEditCallback',action);
end

