function slider = gui_slider(parent,position,min,max,step,value,tooltip,tag,action)

slider = uicontrol('Parent',parent,'Style','slider','Units','pixels','BackgroundColor',[0.8,0.8,0.8],...
          'Position',position,'Min',min,'Max',max,'SliderStep',step,'Value',value,...
          'TooltipString',tooltip,'Fontsize',11,'Tag',tag,'Callback',action);
