function button = gui_tbtn(parent,position,string,fontsize,tooltip,tag,action)

button = uicontrol('Parent',parent,'Style','togglebutton','Units','pixels',...
          'Position',position,'String',string,'TooltipString',tooltip,...
          'Fontsize',fontsize,'Tag',tag,'Callback',action);